<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="lin76001736" failures="1" tests="2" name="farmerApp.FarmCodAccept" time="34.325" errors="0" timestamp="2021-02-28T21:41:14 IST" skipped="0">
  <testcase classname="farmerApp.FarmCodAccept" name="FarmerLogin" time="24.009"/>
  <system-out>
Logging in TIMEOUT EXCEPTION element does not exist after waiting 10 seconds - EMail  </system-out>
  <testcase classname="farmerApp.FarmCodAccept" name="MCcoditemrcv" time="10.316">
    <failure message="TIMEOUT EXCEPTION element does not exist after waiting 10 seconds - " type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: TIMEOUT EXCEPTION element does not exist after waiting 10 seconds - 
at org.testng.Assert.fail(Assert.java:99)
at utilities.ElementManager.elementClick(ElementManager.java:57)
at farmerpageobjects.FarmerCodAcceptPage.fCodaccept(FarmerCodAcceptPage.java:34)
at farmerApp.FarmCodAccept.MCcoditemrcv(FarmCodAccept.java:40)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- MCcoditemrcv -->
  <system-out>
Farmer COD Accept started TIMEOUT EXCEPTION element does not exist after waiting 10 seconds -   </system-out>
</testsuite> <!-- farmerApp.FarmCodAccept -->
